services:
  app:
    build:
      target: dev
    environment:
     # - SPRING_PROFILES_ACTIVE=dev
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - SPRING_APP_PORT=${SPRING_APP_PORT:-8080}
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true
    command: >
      sh -c "/wait-for-it.sh db 3306 -- ./mvnw spring-boot:run -Dspring-boot.run.profiles=${SPRING_PROFILES_ACTIVE:-dev}"
    volumes:
      - ~/.m2:/root/.m2
      - .:/app
    ports:
      - ${SPRING_APP_PORT}:8080